### ISSUE TITLE
Xposed framework showing me ads?!

### ISSUE THREAD

**Issue by ghost** [rovo89/XposedInstaller#469]
I am getting popup Fullscreen ads!
I removed and checked the ads are gone but when i install the framework i get ads after 24 hrs.
Please explain me this problem!

**Comment by xstar97** [comment]
The framework doesn't contain any ads nor  does the Xposed app, more than
likely another app is being malicious.

**Comment by ghost** [comment]
No sir, i strongly support opensource community and use f-droid! And have no app that can show me ads! 
Can you please tell me the best/official source to download xposed framework and installer!

**Comment by xstar97** [comment]
Here or xda... Can't get any official than this:/

**Comment by ViperLiu** [comment]
I had same problem before, and I found that I installed a FAKE Xposed Installer

You can use Packet Capture ( you can install this app via google play ) to capture the traffic and find out which app is showing ads

And after analyzed the FAKE apk with MobSF, I found that the Signer Certificate of the apk is **xposed** instead of **rovo89**

FAKE one:
```
[
  Version: V3
  Subject: CN=xposed
  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11

  Key:  
  Validity: [From: Mon Aug 20 15:35:48 UTC 2018,
               To: Fri Aug 14 15:35:48 UTC 2043]
  Issuer: CN=xposed
  SerialNumber: [    0dc5d244]

Certificate Extensions: 1
[1]: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: F7 56 89 90 32 EA DD 76   C3 59 10 1D 9D 01 19 00  .V..2..v.Y......
0010: 04 28 9B 8E                                        .(..
]
]
```

REAL one:
```
[
[
  Version: V3
  Subject: CN=rovo89
  Signature Algorithm: SHA1withRSA, OID = 1.2.840.113549.1.1.5

  Key:  
  Validity: [From: Wed Jul 04 17:32:14 UTC 2012,
               To: Sun Jun 28 17:32:14 UTC 2037]
  Issuer: CN=rovo89
  SerialNumber: [    4ff47e1e]

]
```
